# Use an official Node.js image as the base image
FROM node:20-alpine AS base

# Set the working directory inside the container
WORKDIR /app

# Install dependencies efficiently
# Copy only the package.json and package-lock.json first
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application files
COPY . .

# Expose the development server port
EXPOSE 3000

# Set the environment to development
ENV NODE_ENV=development

# Run the Next.js development server
CMD ["npm", "run", "dev"]
