name: musika

services:
  db:
    image: postgres:17
    container_name: musika_db
    restart: always
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    env_file:
      ./app/backend/.env
    ports:
      - 5432:5432
    networks:
      - musika_network

  backend:
    build: ./app/backend/
    container_name: musika_backend
    ports:
      - 8000:8000
    volumes:
      - ./app/backend/apps:/app/apps
      - static_data:/app/static
    depends_on:
      - db
    networks:
      - musika_network
    develop:
      watch:
        - action: rebuild
          path: ./app/backend
          target: /app

  frontend:
    build: ./app/frontend/
    container_name: musika_frontend
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/
    volumes:
      - ./app/frontend/node_modules:/app/frontend/node_modules
    # depends_on:
    #   - backend
    networks:
      - musika_network
    develop:
      watch:
        - action: sync
          path: ./app/frontend
          target: /app/frontend
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: musika_pgadmin
    ports:
      - 8888:80
    env_file:
      - ./app/backend/.env
    networks:
      - musika_network
    depends_on:
      - db
  
  nginx:
    container_name: musika_nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./app/nginx/nginx-setup.conf:/etc/nginx/nginx.conf
      - static_data:/app/static
    depends_on:
      - backend
      # - frontend
    networks:
      - musika_network


volumes:
  db_data:
  static_data:

networks:
  musika_network: