# Generated by Django 5.0.9 on 2024-10-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapplication',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
