# Generated by Django 5.0.9 on 2024-10-28 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('relationships', '0002_agentapplication_commission_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_date', models.DateTimeField(auto_now_add=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('revoked', 'Revoked')], default='active', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_offers', to='agents.agent')),
                ('business_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_offers', to='relationships.businessoffer')),
            ],
        ),
    ]
