# Generated by Django 5.0.9 on 2024-10-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_acceptedoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessoffer',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='businessoffer',
            name='offered_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='businessoffer',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
