# Generated by Django 5.0.9 on 2024-10-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_alter_businessoffer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedoffer',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
