# Generated by Django 5.0.9 on 2024-10-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_alter_acceptedoffer_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessoffer',
            name='available_slots',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
