# Generated by Django 5.0.9 on 2024-10-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0006_alter_businessoffer_available_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessagentrelationship',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=50),
        ),
    ]
