# Generated by Django 5.0.9 on 2024-11-01 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_code'),
        ('relationships', '0007_alter_businessagentrelationship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessoffer',
            name='agent',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='agents.agent'),
            preserve_default=False,
        ),
    ]
