# Generated by Django 5.0.9 on 2025-01-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0008_businessoffer_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedoffer',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
