# Generated by Django 5.0.9 on 2025-01-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0009_alter_acceptedoffer_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentapplication',
            name='commission_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='businessagentrelationship',
            name='commission_rate',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='businessoffer',
            name='offered_commission',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
