# Generated by Django 5.0.9 on 2025-01-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0010_alter_agentapplication_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=50),
        ),
    ]
