# Generated by Django 5.0.9 on 2025-01-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0011_alter_businessoffer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('active', 'Active')], default='pending', max_length=50),
        ),
    ]
