# Generated by Django 5.0.9 on 2025-01-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0012_alter_businessoffer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
