# Generated by Django 5.0.9 on 2025-01-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0013_alter_agentapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=50),
        ),
    ]
