# Generated by Django 5.0.9 on 2025-01-10 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_delete_assignedproduct'),
        ('business', '0015_alter_business_code'),
        ('relationships', '0014_alter_businessoffer_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='businessagentrelationship',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='businessoffer',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='AssignedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_products', to='agents.agent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_agents', to='business.product')),
            ],
        ),
    ]
