# Generated by Django 5.0.9 on 2025-01-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_delete_assignedproduct'),
        ('business', '0015_alter_business_code'),
        ('relationships', '0015_alter_agentapplication_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignedProduct',
            new_name='Assignment',
        ),
    ]
