# Generated by Django 5.0.9 on 2025-01-13 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_remove_lead_agent_remove_lead_product_and_more'),
        ('business', '0015_alter_business_code'),
        ('relationships', '0016_rename_assignedproduct_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='business.product'),
        ),
    ]
