# Generated by Django 5.0.9 on 2024-11-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('business_agent', 'Business-Agent Communication'), ('customer_business', 'Customer-Business Support'), ('customer_platform', 'Customer-Platform Support'), ('business_agent_platform', 'Business-Agent-Platform Support')], default='customer_platform', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='was_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communications.role'),
            preserve_default=False,
        ),
    ]
