# Generated by Django 5.0.9 on 2024-10-24 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_messages', to='communications.participant'),
        ),
        migrations.AlterField(
            model_name='message',
            name='was_read_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
