# Generated by Django 5.0.9 on 2024-10-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_message_sender_alter_message_was_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='was_read_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
