# Generated by Django 5.0.9 on 2025-01-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_role_id_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business'), ('platform', 'Platform'), ('agent', 'Agent')], default='customer', max_length=50),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
