# Generated by Django 5.0.9 on 2025-01-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_alter_participant_role_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='role',
        ),
    ]
