# Generated by Django 5.0.9 on 2025-01-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_remove_participant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business'), ('platform', 'Platform'), ('agent', 'Agent')], default='customer', max_length=50),
        ),
    ]
