# Generated by Django 5.0.9 on 2024-10-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_perms',
            field=models.BooleanField(default=False),
        ),
    ]
