# Generated by Django 5.0.9 on 2024-10-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_has_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='has_perms',
        ),
    ]
