# Generated by Django 5.0.9 on 2024-10-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_age_alter_account_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
