# Generated by Django 5.0.9 on 2024-10-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
