# Generated by Django 5.0.9 on 2024-10-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
