# Generated by Django 5.0.9 on 2024-10-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_account_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
