# Generated by Django 5.0.9 on 2024-10-25 13:35

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_account_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name=account.models.generate_code),
        ),
    ]
