# Generated by Django 5.0.9 on 2024-10-25 22:39

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_account_username_alter_account_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(default=account.models.generate_code, editable=False, unique=True),
        ),
    ]
