# Generated by Django 5.0.9 on 2024-12-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_account_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default='null', upload_to='images/accounts/profile'),
            preserve_default=False,
        ),
    ]
