# Generated by Django 5.0.9 on 2025-01-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_account_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country_code',
            field=models.CharField(blank=True, default=263, max_length=4, null=True),
        ),
    ]
