# Generated by Django 5.0.9 on 2024-12-25 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0003_agent_code'),
        ('business', '0011_alter_productimage_variant_alter_profile_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agent_commission_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('agent_earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('completed', 'Completed')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='agents.agent')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='business.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='business.product')),
            ],
        ),
    ]
