# Generated by Django 5.0.9 on 2024-12-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agent_commission_rate',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='agent_earning',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
