# Generated by Django 5.0.9 on 2024-12-25 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_code'),
        ('orders', '0003_alter_order_agent_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='agents.agent'),
        ),
    ]
