# Generated by Django 5.0.9 on 2024-12-25 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_productimage_variant_alter_profile_business'),
        ('orders', '0004_alter_order_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='business.productvariant'),
        ),
    ]
