# Generated by Django 5.0.9 on 2024-12-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='business',
        ),
    ]
