# Generated by Django 5.0.9 on 2024-12-25 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_business_earning_alter_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='agent_commission_rate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
