# Generated by Django 5.0.9 on 2024-12-26 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_productimage_variant_alter_profile_business'),
        ('orders', '0008_remove_order_agent_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='business.business'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('refunded', 'Refunded'), ('completed', 'Completed')], default='active', max_length=50),
        ),
    ]
