# Generated by Django 5.0.9 on 2025-01-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=50),
        ),
    ]
