# Generated by Django 5.0.9 on 2025-01-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_options_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_code',
            field=models.CharField(null=True),
        ),
    ]
