# Generated by Django 5.0.9 on 2025-01-20 13:59

from django.db import migrations
from orders.models import generate_code


def gen_fulfillment_code(apps, schema_editor):
    OrderModel = apps.get_model("orders", "Order")
    for row in OrderModel.objects.all():
        row.fulfillment_code = generate_code()
        row.save(update_fields=["fulfillment_code"])

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_fulfillment_code'),
    ]

    operations = [
        migrations.RunPython(gen_fulfillment_code, reverse_code=migrations.RunPython.noop),
    ]
