# Generated by Django 5.0.9 on 2025-01-20 14:00

import orders.models.utils.generate_unique_code
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_populate_fulfilment_code'),
    ]

    operations = [
      migrations.AlterField(
            model_name='order',
            name='fulfillment_code',
            field=models.CharField(default=orders.models.generate_code, unique=True),
        ),
    ]
