# Generated by Django 5.0.9 on 2024-10-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productanalytics',
            name='product_id',
            field=models.CharField(default='2', max_length=50),
            preserve_default=False,
        ),
    ]
