# Generated by Django 5.0.9 on 2024-10-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_productanalytics_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessanalytics',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
