# Generated by Django 5.0.9 on 2024-10-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_businessanalytics_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productanalytics',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='referring_agent_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('click', 'Click'), ('view', 'View'), ('like', 'Like'), ('cart_add', 'Add To Cart'), ('comment', 'Comment'), ('share', 'Share')], max_length=20),
        ),
    ]
