# Generated by Django 5.0.9 on 2024-11-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_productanalytics_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='browser',
            field=models.CharField(blank=True, default='chrome', max_length=100),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='device',
            field=models.CharField(blank=True, default='mobile', max_length=100),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='os',
            field=models.CharField(blank=True, default='Android', max_length=100),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='source',
            field=models.CharField(choices=[('organic', 'Organic'), ('referral', 'Referral')], max_length=100),
        ),
    ]
