# Generated by Django 5.0.9 on 2025-01-13 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_remove_lead_agent_remove_lead_product_and_more'),
        ('analytics', '0005_alter_acquisition_browser_alter_acquisition_device_and_more'),
        ('business', '0015_alter_business_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='agents.agent')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='user',
        ),
        migrations.DeleteModel(
            name='AgentAnalytics',
        ),
        migrations.DeleteModel(
            name='BusinessAnalytics',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='user',
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='analytics.leadsource'),
        ),
        migrations.DeleteModel(
            name='Acquisition',
        ),
        migrations.DeleteModel(
            name='ProductAnalytics',
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
