# Generated by Django 5.0.9 on 2025-01-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_lead_leadsource_remove_acquisition_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsource',
            name='id',
        ),
        migrations.AddField(
            model_name='leadsource',
            name='short_name',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
