# Generated by Django 5.0.9 on 2025-01-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_remove_leadsource_id_leadsource_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='short_name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
