# Generated by Django 5.0.9 on 2024-10-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_productvariant_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='product_variants', to='business.variantattribute'),
        ),
    ]
