# Generated by Django 5.0.9 on 2024-10-31 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_productvariant_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='attributes',
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='variant',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='business.productvariant'),
            preserve_default=False,
        ),
    ]
