# Generated by Django 5.0.9 on 2024-10-31 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_remove_productvariant_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantattribute',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='business.productvariant'),
        ),
    ]
