# Generated by Django 5.0.9 on 2024-12-05 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_productimage_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='business.productvariant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='business.business'),
        ),
    ]
