# Generated by Django 5.0.9 on 2024-12-29 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_alter_catalog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.business'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.catalog'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.category'),
        ),
    ]
