# Generated by Django 5.0.9 on 2025-01-06 14:28

import business.models.business_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_product_business_alter_product_catalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='code',
            field=models.CharField(default=business.models.business_models.generate_code, max_length=8),
        ),
    ]
