# Generated by Django 5.0.9 on 2024-10-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/agents/profile_pictures/'),
        ),
    ]
