# Generated by Django 5.0.9 on 2024-10-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agentprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='code',
            field=models.CharField(default='HIAGTNEL', max_length=8),
            preserve_default=False,
        ),
    ]
