# Generated by Django 5.0.9 on 2025-01-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='minimum_commission_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
