# Generated by Django 5.0.9 on 2025-01-08 12:42

import agents.models.agent_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agentprofile_minimum_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(default=agents.models.agent_models.generate_code, max_length=8),
        ),
    ]
