# Generated by Django 5.0.9 on 2025-01-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agent_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedProduct',
        ),
    ]
