# Generated by Django 5.0.9 on 2025-01-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_delete_assignedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='product',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
        migrations.DeleteModel(
            name='LeadSource',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
