# Generated by Django 5.0.9 on 2024-10-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='activated',
        ),
    ]
