worker_processes 1;

events { 
    worker_connections 1024; 
}

error_log /var/log/nginx/error.log;

http {
    upstream frontend {
        server frontend:3000;  # Name of the service in docker-compose
    }

    upstream backend {
        server backend:8000;  # Name of the service in docker-compose
    }

    server {
        listen 80;

        access_log /var/log/nginx/access.log;

        location / {
            proxy_pass http://frontend;  # Forward requests to the Next.js app
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }

        location /api/ {
            proxy_pass http://backend;  # Forward API requests to the Django app
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }

        location /static {
            alias /app/static;
            autoindex on;
            include mime.types;
            access_log /var/log/nginx/static_access.log;
            error_log /var/log/nginx/static_error.log debug;
        }

        # skip favicon.ico
        location /favicon.ico {
            access_log off;
            return 204;
        }



    }
}